# Site settings
baseurl = "http://ursulawatercolor.com/"
languageCode = "en-us"
title = "Ursula's Water Color"
theme = "hugo-agency-theme-modified"
googleAnalytics = "UA-75595513-1"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Ursula Stange"
	description = "Here you can find the artwork of water color artist Ursula Stange"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "ursulamitschke1127@gmail.com"


	# Navigation
	[params.navigation]
		brand = "Ursula"
		portfolio = "Portfolio"
		about = "About"
		contact = "Contact"

	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "Ursula's Art Gallery"
		subtitle = "Water Color"
		buttonText = "Show me more"


	# Portfolio section
	[params.portfolio]
        enable = true
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Portfolio"
		subtitle = "Assorted works of art."

		[params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttonText = "Close"


    # About section
	[params.about]
        enable = true
		title = "About the Artist"
		subtitle = "Ursula Stange enjoys producing vibrant and emotional pieces, primarily in the medium of water color."
		endpoint = "What great things may the future hold?"

		# The events will be listed from the top to the bottom.
		# All images are stored under 'static/img/about'.
		# Replace them with your own.
		[[params.about.events]]
			img = "hannover_small.jpg"
			date = "1948"
			title = "Born"
			description = "Born in Hannover, Germany"

		[[params.about.events]]
			img = "art_school_small.jpg"
			date = "1981"
			title = "Art School"
			description = "1981 held her formal introduction to artwork, under the direction of Diethelm Schafer."

		[[params.about.events]]
			img = "today_small.jpg"
			date = "2014-Present"
			title = "Water Color Becomes a Regular Hobby"
			description = "Since 1981, throughout her many travels in Europe, Ursula has gained a unique cross-cultural perspective on various art forms.<br>She hopes that you will enjoy her artwork as much as she enjoyed making it."


	# Contact section
	[params.contact]
        enable = true
		title = "Contact Me"
		subtitle  = "If you wish to find out more, or possibly purchase a piece, feel free to contact me!"
		buttonText = "Send message"

		# 'warning' defines error messages for invalid inputs
		[params.contact.form.name]
			text = "Your Name *"
			warning = "Please enter your name."

		[params.contact.form.email]
			text = "Your Email *"
			warning = "Please enter your email address."

		[params.contact.form.phone]
			text = "Your Phone *"
			warning = "Please enter your phone number."

		[params.contact.form.message]
			text = "Your Message *"
			warning = "Please enter a message."


	# Footer section
# 	[params.footer]
#         enable = true
# 		copyright = "Published under the Apache License 2.0."
#
# 		[[params.footer.social]]
# 			icon = "fa-twitter"
# 			link = "#"
#
# 		[[params.footer.social]]
# 			icon = "fa-facebook"
# 			link = "#"
#
# 		[[params.footer.social]]
# 			icon = "fa-linkedin"
# 			link = "#"
#
# 		[[params.footer.quicklinks]]
# 			text = "Privacy Policy"
# 			link = "#"
#
# 		[[params.footer.quicklinks]]
# 			text = "Terms of Use"
# 			link = "#"
